language: rust
sudo: required
dist: trusty
rust:
  - stable
  - beta
  - nightly

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

before_install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable

install:
  - npm install --no-progress

matrix:
  allow_failures:
    - rust: nightly

os:
  - linux

script: mocha
