[package]
name = "ratel"
version = "0.0.4"
authors = ["Matthias Thoemmes <git@gmx.org>"]
license = "MIT"

[lib]
name = "honey_badger_cli"
crate-type = ["dylib"]

[dependencies]
neon = "0.1"
ratel = "0.2.3"

#[dependencies.ratel]
#path = "../../ratel-core"
