[package]
name = "honey-badger-cli"
version = "0.0.3"
authors = ["Matthias Thoemmes <git@gmx.org>"]
license = "MIT"

[lib]
name = "honey_badger_cli"
crate-type = ["dylib"]

[dependencies]
neon = "0.1"
badger = "0.2.1"

#[dependencies.badger]
#path = "../../HoneyBadger"
